# Generated by Django 4.2.6 on 2023-10-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tooodooo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
