# Generated by Django 4.2.6 on 2023-10-08 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tooodooo', '0003_tasks_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='state',
        ),
    ]
