# Generated by Django 4.2.6 on 2023-11-07 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tooodooo', '0009_tasks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
